
- name: install awslogs
  yum: name=awslogs state=latest disable_gpg_check=yes

- name: copy conf files
  template: src={{ item }}.j2 owner=root dest=/etc/awslogs/{{ item }}
  with_items:
    - awscli.conf
    - awslogs.conf

- name: create directory
  file: path=/home/ec2-user/awslogs/state owner=ec2-user state=directory mode=0775

- name: create state log file
  file: path=/home/ec2-user/awslogs/state/agent-state owner=ec2-user state=touch mode=0775

- name: start agent
  service: name=awslogs state=started
