---
- name: create deploy directory
  file: path={{ deploy_dir }} owner=root group=root mode=0755 state=directory

- name: create app directory
  file: path={{ item.dir }} owner=ec2-user mode=0755 state=directory
  with_items:
    - { dir: '{{ app_root_dir }}' }
    - { dir: '{{ pidfile_dir }}' }
    - { dir: '{{ log_dir }}' }
